# Generated by Django 4.1.7 on 2023-03-29 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regex',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.UUID('dd65ab29-84a9-4a1f-8863-80869fcbb434'), primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
