# Generated by Django 4.1.7 on 2023-03-29 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regex',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6e9e0931-f8de-4396-bad7-6b14d86e939a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
