# Generated by Django 4.1.7 on 2023-03-30 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('regex', '0004_regex_regex_alter_regex_id_alter_regex_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regex',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
